# Generated by Django 5.2.6 on 2025-09-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_admin'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.conductor', verbose_name='Conductor Asignado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
