# Generated by Django 4.2.24 on 2025-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_pedido_conductor_pedido_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_curso', 'En Curso'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
