# Generated by Django 4.2.24 on 2025-10-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='codigo_postal',
        ),
    ]
