# Generated by Django 4.2.24 on 2025-11-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0004_remove_userprofile_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que envió el mensaje (si está autenticado)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
