# Generated by Django 4.2.24 on 2025-09-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('licencia', models.CharField(max_length=50, verbose_name='Licencia de Conducir')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('descanso', 'En Descanso'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=50, unique=True, verbose_name='Número de Guía')),
                ('descripcion_carga', models.TextField(verbose_name='Descripción de la Carga')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('volumen_m3', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Volumen (m³)')),
                ('direccion_recogida', models.TextField(verbose_name='Dirección de Recogida')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('contacto_recogida', models.CharField(max_length=200, verbose_name='Contacto Recogida')),
                ('contacto_entrega', models.CharField(max_length=200, verbose_name='Contacto Entrega')),
                ('telefono_recogida', models.CharField(max_length=20, verbose_name='Teléfono Recogida')),
                ('telefono_entrega', models.CharField(max_length=20, verbose_name='Teléfono Entrega')),
                ('fecha_recogida_programada', models.DateTimeField(verbose_name='Fecha de Recogida Programada')),
                ('fecha_entrega_programada', models.DateTimeField(verbose_name='Fecha de Entrega Programada')),
                ('fecha_recogida_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recogida Real')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Envío')),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Declarado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente', verbose_name='Cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.conductor', verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Ruta')),
                ('origen', models.CharField(max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distancia (km)')),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tiempo Estimado (horas)')),
                ('costo_combustible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de Combustible')),
                ('peajes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Peajes')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('camion', 'Camión'), ('furgoneta', 'Furgoneta'), ('trailer', 'Trailer'), ('motocicleta', 'Motocicleta')], max_length=20, verbose_name='Tipo')),
                ('capacidad_peso', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Peso (kg)')),
                ('capacidad_volumen', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Volumen (m³)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('kilometraje', models.IntegerField(default=0, verbose_name='Kilometraje')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='logistics.envio', verbose_name='Envío')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de Envío',
                'verbose_name_plural': 'Seguimientos de Envío',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='PedidoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('descripcion', models.TextField(verbose_name='Descripción de la carga')),
                ('direccion_recogida', models.TextField(verbose_name='Dirección de Recogida')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Estimado (kg)')),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Declarado')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Estimado')),
                ('fecha_recogida_deseada', models.DateTimeField(verbose_name='Fecha de Recogida Deseada')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente', verbose_name='Cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.conductor', verbose_name='Conductor')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.ruta', verbose_name='Ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Pedido de Transporte',
                'verbose_name_plural': 'Pedidos de Transporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.ruta', verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='envio',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.vehiculo', verbose_name='Vehículo'),
        ),
    ]
