# Generated by Django 4.2.24 on 2025-09-15 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.CreateModel(
            name='PedidoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('descripcion', models.TextField(verbose_name='Descripción de la carga')),
                ('direccion_recogida', models.TextField(verbose_name='Dirección de Recogida')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Estimado (kg)')),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Declarado')),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Estimado')),
                ('fecha_recogida_deseada', models.DateTimeField(verbose_name='Fecha de Recogida Deseada')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente', verbose_name='Cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.conductor', verbose_name='Conductor')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.ruta', verbose_name='Ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Pedido de Transporte',
                'verbose_name_plural': 'Pedidos de Transporte',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
