# Generated by Django 5.2.6 on 2025-09-25 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('nivel_acceso', models.CharField(choices=[('superadmin', 'Super Administrador'), ('admin', 'Administrador'), ('moderador', 'Moderador')], default='admin', max_length=20, verbose_name='Nivel de Acceso')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de Contratación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['nombre'],
            },
        ),
    ]
