# Generated by Django 4.2.24 on 2025-10-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_admin'),
    ]

    operations = [
    ]
