# Generated by Django 4.2.24 on 2025-10-28 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0003_auto_20251028_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='capacidad_peso',
            new_name='capacidad_kg',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad_volumen',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default='Blanco', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='gasolina', max_length=20, verbose_name='Combustible'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.conductor', verbose_name='Conductor Asignado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Chasis'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número de Motor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('camion', 'Camión'), ('furgon', 'Furgón'), ('camioneta', 'Camioneta'), ('motocicleta', 'Motocicleta')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='PedidoTransporte',
        ),
    ]
