# Generated by Django 4.2.24 on 2025-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_rename_capacidad_peso_vehiculo_capacidad_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='año_vehiculo_temporal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='color_vehiculo_temporal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='marca_vehiculo_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='modelo_vehiculo_temporal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='placa_temporal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa Temporal'),
        ),
    ]
