# Generated by Django 4.2.24 on 2025-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_conductor_año_vehiculo_temporal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='capacidad_kg_temporal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='combustible_temporal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Combustible Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_chasis_temporal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chasis Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_motor_temporal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motor Temporal'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipo_vehiculo_temporal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Temporal'),
        ),
    ]
