# Generated by Django 4.2.24 on 2025-10-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_conductor_capacidad_kg_temporal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_postal',
        ),
    ]
