# Generated by Django 4.2.24 on 2025-10-29 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0007_remove_cliente_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
