# Generated by Django 4.2.24 on 2025-11-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_envio_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='ruta',
        ),
        migrations.AddField(
            model_name='conductor',
            name='apellidos',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='nombres',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='envio',
            name='destino',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Destino'),
        ),
        migrations.AddField(
            model_name='envio',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Distancia (km)'),
        ),
        migrations.AddField(
            model_name='envio',
            name='origen',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Origen'),
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
