# Generated by Django 4.2.24 on 2025-11-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_conductor_options_remove_conductor_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_chasis',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='numero_motor',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_motor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad del Motor (CC)'),
        ),
    ]
