# Generated by Django 4.2.24 on 2025-11-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_vehiculo_numero_chasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='capacidad_motor_temporal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Capacidad Motor Temporal'),
        ),
    ]
