# Generated by Django 4.2.24 on 2025-11-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_conductor_capacidad_motor_temporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
